- README.md
> readme: use virtualenv for BugZoo

- README.md
Not sure if my update is correct, but it would sound more consistent.
But I could not yet check if `fix` switches to buggy or to fixed.
> Fix and unfix mismatched?

- .yamllint.yml
- geometry2/b4dc23c.bug
- kobuki/17560e9/17560e9.bug
- turtlebot/61a75df/61a75df.bug
This fails Travis right now, but that is expected.
> WIP: update yamllint config

- README.md
> readme: make sure Python3 headers are installed

- mavros/263650d/263650d.bug
- mavros/263650d/deps.rosinstall
- mavros/263650d/test.sh
- robust.bugzoo.yml
We do have a test case for this particular bug, but in the interest of expediency, this PR does not include the test case.
> Added BugZoo instructions for mavros-263650d (fixes #203)

- scripts/README.md
As per subject.
Initially I hadn't seen the `requirements.txt` file, so both scripts refused to work. Hopefully this avoids frustrating future users :)
> Add setup steps for utility scripts.

- scripts/README.md
> scripts/readme: remove spurious single quote.

- scripts/README.md
> Explicitly mention name of time-machine binary.

- doc/progress.csv
- mavros/b6b9754/b6b9754.bug
- mavros/b6b9754/deps.rosinstall
- mavros/b6b9754/test.sh
> mavros-b6b9754

- Dockerfile
- scripts/build-bugzoo.py
Should address current issues with #262.
> Added support for multiple PUTs (assuming a single fork)

- geometry2/0af76d5/0af76d5.bug
- geometry2/0af76d5/deps.rosinstall
> WIP: geometry2/0af76d5

- mavros/7c6514d/7c6514d.bug
As per subject.
The PR contains many more commits, but also the 'fix commit'.
> 7c6514d: add PR link.

- motoman/9df36cb/9df36cb.bug
> 9df36cb: amend bug description.

- care-o-bot/ac6a181/ac6a181.bug
> ac6a181: amend description.

- turtlebot/9ffffca/9ffffca.bug
> 9ffffca: amend description.

- mavros/ff581a0/ff581a0.bug
> ff581a0: amend description.

- mavros/e1a8005/e1a8005.bug
> e1a8005: amend description.

- mavros/b96bf67/b96bf67.bug
> b96bf67: amend description.

- care-o-bot/e9ed0f8/e9ed0f8.bug
As per subject.
Some copy-pasta from other care-o-bot bugs here I believe.
> e9ed0f8: amend description.

- kobuki/pre_2013_04_22/4ea5ea7/4ea5ea7.bug
As per subject.
The commit comment contains additional information.
> 4ea5ea7: xacros contain models, not tags.

- kobuki/496aac8/496aac8.bug
- scripts/robust.json
As per discussion in the meeting on MAR 18.
> Downgrade severity of koboki/496aac8.bug to not-a-bug

- requirements.dev.txt
- scripts/gdocs_reader.py
- scripts/requirements.txt
cleaned up version of https://github.com/robust-rosin/robust/pull/385
> Reads gdocs and adds fault and falure codes to bugs
